### ISSUE TITLE
`IsVisible` extension mistyped as `IsVisble`

### ISSUE THREAD

**Issue by greystate** [callumbwhyte/umbraco-search-extensions#3]
https://github.com/callumbwhyte/umbraco-search-extensions/blob/a5fed24e8661204803ff844fada93b0ac9f5e2c4/src/Our.Umbraco.Extensions.Search/QueryExtensions.cs#L34

Looks like a typo got sneaked in - This should be `IsVisible()` I guess?

**Comment by callumbwhyte** [comment]
Hey @greystate,

This is (finally) fixed in v1.5.0! Thanks for using Search Extensions :-)

Cheers,
Callum
