### ISSUE TITLE
Version conflict when installing from nuget

### ISSUE THREAD

**Issue by frederiktoft** [callumbwhyte/umbraco-search-extensions#6]
I am trying to add v2.0.0 of this package to an Umbraco 10.2.1 installation, but there is this following version conflict error:

```
Version conflict detected for Umbraco.Cms.Examine.Lucene. Install/reference Umbraco.Cms.Examine.Lucene 10.2.1 directly to project xxx.zzz.Docs.Web to resolve this issue. 
 xxx.zzz.Docs.Web -> Umbraco.Cms 10.2.1 -> Umbraco.Cms.Web.Website 10.2.1 -> Umbraco.Cms.Web.Common 10.2.1 -> Umbraco.Cms.Examine.Lucene (>= 10.2.1) 
 xxx.zzz.Docs.Web -> Our.Umbraco.Extensions.Search 2.0.0 -> Umbraco.Cms.Examine.Lucene (>= 9.0.1 && < 10.0.0).	xxx.zzz.Docs.Web
```

**Comment by callumbwhyte** [comment]
Hey @frederiktoft,

Previously this package did not support Umbraco v10 - as of [v3.0.0](https://github.com/callumbwhyte/umbraco-search-extensions/releases/tag/release-3.0.0) it now does! Hopefully this solves your issue.

Cheers,
Callum
